### ISSUE TITLE
library design

### ISSUE THREAD

**Issue by nilsnolde** [jonathf/pyvroom#15]
currently `_vroom_xx.so` is installed in the root of `site-packages` while the python stuff is in `site-packages/vroom`. what do you think about taking it all into the `vroom` directory? a little bit cleaner IMO. then it's a relative import for the extension `import ._vroom`. 

just bit me when pip didn't properly uninstall for whatever reason and I manually deleted `vroom` but didn't see the `_vroom` lib.

**Comment by jonathf** [comment]
Yea, agrreed,å that is a good idea.

Either feel free to fix it yourself, or I'll get around to it later.
