### ISSUE TITLE
musllinux wait a little?

### ISSUE THREAD

**Issue by nilsnolde** [jonathf/pyvroom#16]
the musllinux builds take the majority of CI time, trumping even windows with openssl source builds etc. 

the main issue seems to be that numpy has no binary wheels yet and the source build takes a good 6 mins for each python minor version. the issue is https://github.com/numpy/numpy/issues/20089 but not sure, doesn't look like there's been much traction. though they apparently already transitioned to use cibuildwheel for distribution but don't use it to build musllinux yet..

just a question if those wheels are important to you or if it could wait until there's numpy wheels for alpine? would save a few CI hours:)

**Comment by jonathf** [comment]
Musllinux should already be turned off in pyproject.toml.
Haven't checked. Are you saying it is building on github actions?

**Comment by nilsnolde** [comment]
that's what I thought, but maybe I was looking at an older build. you're right, it's actually turned off in the toml.

**Comment by nilsnolde** [comment]
actually yes, see https://github.com/jonathf/pyvroom/actions/runs/1638879674. took > 30 mins for linux. the last full release build built all musllinux wheels
